config/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),

    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import SendConfirmCodeView, ConfirmCodeView, SurveyPageView

app_name = UsersConfig.name

urlpatterns = [
    path('', SurveyPageView.as_view(), name='survey'),
    # path('login/', LoginPageView.as_view(), name='login'),
    path('send-code/', SendConfirmCodeView.as_view(), name='send_code'),
    path('confirm-code/', ConfirmCodeView.as_view(), name='confirm_code'),
]

users/models.py
import random
import string

from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, phone_number, password=None, **extra_fields):
        if not phone_number:
            raise ValueError("Введите номер телефона")
        user = self.model(phone_number=phone_number, **extra_fields)
        user.set_password(password if password else '')
        user.save(using=self._db)
        return user

    def create_superuser(self, phone_number, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)
        return self.create_user(phone_number=phone_number, password=password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    phone_number = models.CharField(max_length=15, unique=True, verbose_name='Номер телефона')
    # password = models.CharField(max_length=30, blank=True, null=True, verbose_name='Пароль')
    confirm_code = models.CharField(max_length=4, blank=True, null=True, verbose_name='Код подтверждения')
    joined_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')
    is_active = models.BooleanField(default=False, verbose_name='Активен')
    is_staff = models.BooleanField(default=False, verbose_name='Доступ к админке')
    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = []
    objects = UserManager()

    def __str__(self):
        return f"{self.phone_number}, {self.confirm_code}"

    def save(self, *args, **kwargs):
        if not self.confirm_code:
            self.confirm_code = ''.join(random.choices(string.ascii_letters + string.digits, k=4))
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/views.py
import logging
import random
import string

import requests
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from django.views.generic import TemplateView

from config import settings
from users.models import User

logger = logging.getLogger(__name__)


# class LoginPageView(TemplateView):
#     template_name = 'survey/login.html'


class SendConfirmCodeView(View):
    def get(self, request):
        return render(request, 'survey/login.html')

    def post(self, request):
        print("Функция отправки кода вызвана")
        phone_number = request.POST.get('phone_number')

        if not phone_number:
            return Response({'error': 'Номер телефона обязателен'}, status=status.HTTP_400_BAD_REQUEST)

        logger.info(f"Попытка создать пользователя с номером: {phone_number}")

        confirm_code = ''.join(random.choices(string.digits, k=4))

        try:
            user, created = User.objects.get_or_create(phone_number=phone_number)
            logger.info(f"Пользователь: {user.phone_number}, Создан: {created}")
        except Exception as e:
            logger.error(f"Ошибка при создании пользователя: {e}")
            return Response({"error": "Ошибка при создании пользователя"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        user.confirm_code = confirm_code
        user.save()
        print(f"Пользователь: {user.phone_number}, Код: {user.confirm_code}")

        sms_url = 'https://sms.ru/sms/send'
        params = {
            'api_id': settings.SMS_API,
            'to': phone_number,
            'msg': f"Ваш код подтверждения: {confirm_code}",
            'json': 1
        }
        logger.info(f"Отправка SMS на номер {phone_number}")
        response = requests.get(sms_url, params=params)
        logger.info(f"Ответ от SMS-сервиса: {response.status_code} - {response.json()}")

        if response.status_code == 200 and response.json().get('status') == 'OK':
            logger.info(f"Код подтверждения отправлен на номер {phone_number}")
            redirect_url = reverse('users:confirm_code') + f"?phone_number={phone_number}"
            logger.info(f"Перенаправление на: {redirect_url}")
            return redirect(redirect_url)
            # return render(request, 'confirm.html', {'phone_number': phone_number})
            # return Response({'message': 'Код отправлен'}, status=status.HTTP_200_OK)
        else:
            logger.error(f"Ошибка при отправке SMS: {response.text}")
            return render(request, 'survey/confirm.html', {'error': 'Ошибка при отправке SMS'})
            # return Response({'error': 'Ошибка при отправке SMS'}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


class ConfirmCodeView(APIView):
    def get(self, request):
        phone_number = request.GET.get('phone_number')
        return render(request, 'survey/confirm.html', {'phone_number': phone_number})

    def post(self, request):
        # phone_number = request.data.get('phone_number')
        confirm_code = request.data.get('confirm_code')

        if  not confirm_code:
            return Response({'error': 'Введите код подтверждения!'},
                            status=status.HTTP_400_BAD_REQUEST)
        logger.info(f"Поиск пользователя с кодом: {confirm_code}")
        try:
            user = User.objects.get(confirm_code=confirm_code)
            logger.info(f"Пользователь найден: {user.phone_number}, Код: {user.confirm_code}")
        except User.DoesNotExist:
            logger.error(f"Пользователь с кодом {confirm_code} не найден")
            return Response({"error": "Пользователь с таким номером телефона не найден"},
                            status=status.HTTP_404_NOT_FOUND)

        # user = get_object_or_404(User, phone_number=phone_number)
        if user.confirm_code == confirm_code:
            user.is_active = True
            user.save()
            return redirect('users:survey')
            # return Response({'message': 'Код подтвержден'}, status=status.HTTP_200_OK)
        else:
            return Response({'error': 'Неверный код подтверждения'}, status=status.HTTP_400_BAD_REQUEST)


class SurveyPageView(TemplateView):
    def get_template_names(self):
        return ['survey/survey.html']

templates/survey/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Шаблон формы входа · Bootstrap v5.0</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
</head>
<body class="text-center">
<main class="form-signin">
    {% block content %}
    {% endblock %}
    <p class="mt-5 mb-3 text-muted">&copy; 2025</p>
</main>
</body>
</html>

templates/survey/confirm.html
{% extends 'survey/base.html' %}

{% block content %}
      <label for="floatingPassword"></label>
<form method="post" action="{% url 'users:confirm_code' %}">
    <div class="form-floating">
    {% csrf_token %}
        <input type="hidden" name="phone_number" value="{{ request.GET.phone_number }}">
    <div class="form-floating">
        <input type="text" class="form-control" name="confirm_code" placeholder="Введите 4х-значный код" required>
        <label for="floatingPassword"></label>
    </div>
    <button type="submit" class="btn btn-outline-primary">Подтвердить</button>
    </div>
</form>
{% endblock %}

templates/survey/login.html
{% extends 'survey/base.html' %}

{% block content %}
      <label for="floatingPassword"></label>
<form method="post" action="{% url 'users:send_code' %}">
    <div class="form-floating">
    {% csrf_token %}
    <input type="text" class="form-control" name="phone_number" id="phone_number" placeholder="Введите номер телефона" required>
    <div class="form-floating">
        <label for="floatingPassword"></label>
    </div>
    <button type="submit" class="btn btn-outline-primary">Отправить код</button>
    </div>
</form>
{% endblock %}

templates/survey/survey.html
{% extends 'survey/base.html' %}
{% block content %}
<div class="mx-0 mx-sm-auto">
  <div class="card">
    <div class="card-header bg-primary">
      <h5 class="card-title text-white mt-2" id="exampleModalLabel">BreadBerry - BakeryShop</h5>
    </div>
    <div class="modal-body">
      <div class="text-center">
        <i class="far fa-file-alt fa-4x mb-3 text-primary"></i>
        <p>
          <strong>Ответьте на несколько вопросов</strong>
        </p>
        <p>
          Мы придумали для вас опросник
          <strong>Интересно какими будут ваши ответы</strong>
        </p>
      </div>

      <hr />

      <form class="px-4" action="">
        <p class="text-center"><strong>По пятибальной шкале, как вы оцените наши новые зерна?</strong></p>

        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example1" />
          <label class="form-check-label" for="radio3Example1">
            Очень хорошо
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example2" />
          <label class="form-check-label" for="radio3Example2">
            Хорошо
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example3" />
          <label class="form-check-label" for="radio3Example3">
            Пойдет
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example4" />
          <label class="form-check-label" for="radio3Example4">
            Такое себе
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example5" />
          <label class="form-check-label" for="radio3Example5">
            Старые намного лучше
          </label>
        </div>
        <hr />
        <p class="text-center"><strong>По пятибальной шкале, как вы оцените наши новые зерна?</strong></p>

        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example1" />
          <label class="form-check-label" for="radio3Example1">
            Очень хорошо
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example2" />
          <label class="form-check-label" for="radio3Example2">
            Хорошо
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example3" />
          <label class="form-check-label" for="radio3Example3">
            Пойдет
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example4" />
          <label class="form-check-label" for="radio3Example4">
            Такое себе
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example5" />
          <label class="form-check-label" for="radio3Example5">
            Старые намного лучше
          </label>
        </div>

        <hr />
        <p class="text-center"><strong>По пятибальной шкале, как вы оцените наши новые зерна?</strong></p>

        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example1" />
          <label class="form-check-label" for="radio3Example1">
            Очень хорошо
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example2" />
          <label class="form-check-label" for="radio3Example2">
            Хорошо
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example3" />
          <label class="form-check-label" for="radio3Example3">
            Пойдет
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example4" />
          <label class="form-check-label" for="radio3Example4">
            Такое себе
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example5" />
          <label class="form-check-label" for="radio3Example5">
            Старые намного лучше
          </label>
        </div>

        <hr />
        <p class="text-center"><strong>По пятибальной шкале, как вы оцените наши новые зерна?</strong></p>

        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example1" />
          <label class="form-check-label" for="radio3Example1">
            Очень хорошо
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example2" />
          <label class="form-check-label" for="radio3Example2">
            Хорошо
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example3" />
          <label class="form-check-label" for="radio3Example3">
            Пойдет
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example4" />
          <label class="form-check-label" for="radio3Example4">
            Такое себе
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example5" />
          <label class="form-check-label" for="radio3Example5">
            Старые намного лучше
          </label>
        </div>

        <hr />
        <p class="text-center"><strong>По пятибальной шкале, как вы оцените наши новые зерна?</strong></p>

        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example1" />
          <label class="form-check-label" for="radio3Example1">
            Очень хорошо
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example2" />
          <label class="form-check-label" for="radio3Example2">
            Хорошо
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example3" />
          <label class="form-check-label" for="radio3Example3">
            Пойдет
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example4" />
          <label class="form-check-label" for="radio3Example4">
            Такое себе
          </label>
        </div>
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example5" />
          <label class="form-check-label" for="radio3Example5">
            Старые намного лучше
          </label>
        </div>

        <p class="text-center"><strong>Что бы мы могли улучшить??</strong></p>

        <!-- Message input -->
        <div data-mdb-input-init class="form-outline mb-4">
          <textarea class="form-control" id="form4Example3" rows="4"></textarea>
          <label class="form-label" for="form4Example3">Спасибо, что остаетесь частью BreadBerry</label>
        </div>
      </form>
    </div>
<!--    </div>-->
<!--  </div>-->
<!--    <hr />-->
<!--    <div class="card-footer text-end">-->
      <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary">Submit</button>
    </div>
  </div>
<!--</div>-->
{% endblock %}